//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralToDoListTable
    {
        public int ToDoId { get; set; }
        public int UserName { get; set; }
        public string TaskName { get; set; }
        public string TaskFeedBack { get; set; }
        public int TaskId { get; set; }
        public bool IsTaskComplete { get; set; }
        public int UnitId { get; set; }
        public System.DateTime CompletionDate { get; set; }
    
        public virtual TaskTable TaskTable { get; set; }
        public virtual UnitTable UnitTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
