//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GeneralToDoListTable
    {
        public int ToDoId { get; set; }

        [Display(Name = "User Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " User Name field required")]    
        public int UserName { get; set; }
        [Display(Name = "Task Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " Task Name field required")]
        public string TaskName { get; set; }

        [Display(Name = "Task FeedBack")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " Task FeedBack field required")]
        public string TaskFeedBack { get; set; }
        [Display(Name = "Task Reference")]
        public int TaskId { get; set; }
        [Display(Name = "Task Status")]
        public bool IsTaskComplete { get; set; }
        [Display(Name = "Unit Name")]
        public int UnitId { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime CompletionDate { get; set; }
    
        public virtual TaskTable TaskTable { get; set; }
        public virtual UnitTable UnitTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
