//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PersonalToDoListTable
    {
        public int PToDoListId { get; set; }

        [Display(Name = "User Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " User Name field required")]
   
        public string UserName { get; set; }
        [Display(Name = "Task Name ")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " Task Namefield required")]
        public string TaskName { get; set; }
        [Display(Name = "Task Feedback")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " TaskFeedbackfield required")]
        public string TaskFeedback { get; set; }
    }
}
