//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PersonalToDoListTable
    {
        public int PToDoListId { get; set; }
        public string UserName { get; set; }
        [Display(Name = "Task Name")]
        [MaxLength(20, ErrorMessage = "please give a shorter sentence")]
        [MinLength(6, ErrorMessage = "minimum characters are 6 please try again")]
        public string TaskName { get; set; }
        [Display(Name = "Task description")]
        [DataType(DataType.MultilineText)]
        [MaxLength(20, ErrorMessage = "please give a shorter sentence")]
        [MinLength(6, ErrorMessage = "minimum characters are 6 please try again")]
        public string TaskFeedback { get; set; }
    }
}
