//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RolesTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolesTable()
        {
            this.UsersRolesTables = new HashSet<UsersRolesTable>();
        }
    
        public int RolesId { get; set; }
        [Display(Name = "Role Name")]
        [MaxLength(20, ErrorMessage = "please give a shorter sentence")]
        [MinLength(6, ErrorMessage = "minimum characters are 6 please try again")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " Role Name field required")]
        public string RoleName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersRolesTable> UsersRolesTables { get; set; }
    }
}
