//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TaskTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskTable()
        {
            this.GeneralToDoListTables = new HashSet<GeneralToDoListTable>();
            this.UserReportsTables = new HashSet<UserReportsTable>();
        }
        public int TaskId { get; set; }
        public int UserId { get; set; }
        [Display(Name = "Task Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Role Name field required")]
        public string TaskName { get; set; }
        [Display(Name = "TASK RESULTS / FEEDBACK")]
        [DataType(DataType.MultilineText)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "FEEDBACK field required")]
        public string FeedBack { get; set; }
        [Display(Name = "Task Description")]
        [DataType(DataType.MultilineText)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Description field required")]
        public string BodyContent { get; set; }
        public bool TaskStatus { get; set; }
        [Display(Name = "Task Start Time")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " Task Start Time field required")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime TastStartTime { get; set; }
        [Display(Name = "Task End Time")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " Deadline field required")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime TaskEndTime { get; set; }
        [Display(Name = "Unit Name")]
        public int UnitId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralToDoListTable> GeneralToDoListTables { get; set; }
        public virtual UnitTable UnitTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserReportsTable> UserReportsTables { get; set; }
    }
}
