//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class UserReportsTable
    {
        public int Reportid { get; set; }

        [Display(Name = "USER SUBMITTING REPORT")]
       
        public int Userid { get; set; }
        [Display(Name = "Task Reference")]
     

        public int TaskId { get; set; }

        [Display(Name = "Report Name")]
       
        public string Title { get; set; }
        [Display(Name ="Download Report Document")]
      
        public string Report { get; set; }


        public virtual TaskTable TaskTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
